"""Initial migration

Revision ID: 0a42a2d07b03
Revises: 
Create Date: 2025-03-21 18:44:44.589169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a42a2d07b03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.drop_constraint('job_history_job_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_history_job_id_fkey', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
