"""Add numero_trabajo to jobs

Revision ID: 74d868b7ca1c
Revises: 92a83064cc19
Create Date: 2025-04-08 14:20:14.219588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d868b7ca1c'
down_revision = '92a83064cc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_numero_trabajo')
        batch_op.create_unique_constraint(None, ['numero_trabajo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_jobs_numero_trabajo', ['numero_trabajo'], unique=True)

    # ### end Alembic commands ###
