"""Add numero_trabajo column to jobs table

Revision ID: 92a83064cc19
Revises: 0a42a2d07b03
Create Date: 2025-04-08 14:13:53.387585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92a83064cc19'
down_revision = '0a42a2d07b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('comentario')
        batch_op.drop_column('autor')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('filetype', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'])
        batch_op.drop_column('nombre_archivo')
        batch_op.drop_column('fecha_subida')
        batch_op.drop_column('ruta_archivo')

    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('comentario')
        batch_op.drop_column('estado_anterior')
        batch_op.drop_column('estado_nuevo')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_trabajo', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_numero_trabajo'), ['numero_trabajo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_numero_trabajo'))
        batch_op.drop_column('numero_trabajo')

    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado_nuevo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado_anterior', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('details')
        batch_op.drop_column('action')

    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_archivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_subida', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_archivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('filesize')
        batch_op.drop_column('filetype')
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')

    with op.batch_alter_table('job_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('autor', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('contenido')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
